title: "Priyadarshini Chettiar"
email: priyadarshinichettiar@gmail.com
description: I'm a Programming enthusiast. Currently learning ReactJs and Flutter. I'm a blogger too.
baseurl: "/" 
url: "https://priyadarshu.github.io" 
twitter_username: priya_darshu_
github_username:  priyadarshu

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
